# coding: utf-8

"""
    Kubeflow Pipelines API

    This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.

    Contact: kubeflow-pipelines@google.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kfp_server_api
from kfp_server_api.models.pipeline_task_detail_input_outputs import PipelineTaskDetailInputOutputs  # noqa: E501
from kfp_server_api.rest import ApiException

class TestPipelineTaskDetailInputOutputs(unittest.TestCase):
    """PipelineTaskDetailInputOutputs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PipelineTaskDetailInputOutputs
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kfp_server_api.models.pipeline_task_detail_input_outputs.PipelineTaskDetailInputOutputs()  # noqa: E501
        if include_optional :
            return PipelineTaskDetailInputOutputs(
                parameters = [
                    kfp_server_api.models.input_outputs_parameter.InputOutputsParameter(
                        value = '0', 
                        name = '0', 
                        producer = kfp_server_api.models.input_outputs_io_producer.InputOutputsIOProducer(
                            task_name = '0', 
                            key = '0', ), )
                    ], 
                artifacts = [
                    kfp_server_api.models.input_outputs_io_artifact.InputOutputsIOArtifact(
                        parameter_name = '0', 
                        value = kfp_server_api.models.note_to_be_confused_with_runtime_artifact_in_pipelinespec.Note to be confused with RuntimeArtifact in pipelinespec(
                            artifact_id = '0', 
                            name = '0', 
                            description = '0', 
                            type = 'TYPE_UNSPECIFIED', 
                            uri = '0', 
                            metadata = {
                                'key' : None
                                }, 
                            number_value = 1.337, 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            namespace = '0', ), 
                        producer = kfp_server_api.models.input_outputs_io_producer.InputOutputsIOProducer(
                            task_name = '0', 
                            key = '0', ), )
                    ]
            )
        else :
            return PipelineTaskDetailInputOutputs(
        )

    def testPipelineTaskDetailInputOutputs(self):
        """Test PipelineTaskDetailInputOutputs"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
