# coding: utf-8

"""
    Kubeflow Pipelines API

    This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.

    Contact: kubeflow-pipelines@google.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kfp_server_api.configuration import Configuration


class InputOutputsIOArtifact(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'parameter_name': 'str',
        'value': 'V2beta1Artifact',
        'producer': 'InputOutputsIOProducer'
    }

    attribute_map = {
        'parameter_name': 'parameter_name',
        'value': 'value',
        'producer': 'producer'
    }

    def __init__(self, parameter_name=None, value=None, producer=None, local_vars_configuration=None):  # noqa: E501
        """InputOutputsIOArtifact - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._parameter_name = None
        self._value = None
        self._producer = None
        self.discriminator = None

        if parameter_name is not None:
            self.parameter_name = parameter_name
        if value is not None:
            self.value = value
        if producer is not None:
            self.producer = producer

    @property
    def parameter_name(self):
        """Gets the parameter_name of this InputOutputsIOArtifact.  # noqa: E501

        Optional, this is only included on Runtime Tasks when the parameter name is known.  # noqa: E501

        :return: The parameter_name of this InputOutputsIOArtifact.  # noqa: E501
        :rtype: str
        """
        return self._parameter_name

    @parameter_name.setter
    def parameter_name(self, parameter_name):
        """Sets the parameter_name of this InputOutputsIOArtifact.

        Optional, this is only included on Runtime Tasks when the parameter name is known.  # noqa: E501

        :param parameter_name: The parameter_name of this InputOutputsIOArtifact.  # noqa: E501
        :type parameter_name: str
        """

        self._parameter_name = parameter_name

    @property
    def value(self):
        """Gets the value of this InputOutputsIOArtifact.  # noqa: E501


        :return: The value of this InputOutputsIOArtifact.  # noqa: E501
        :rtype: V2beta1Artifact
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this InputOutputsIOArtifact.


        :param value: The value of this InputOutputsIOArtifact.  # noqa: E501
        :type value: V2beta1Artifact
        """

        self._value = value

    @property
    def producer(self):
        """Gets the producer of this InputOutputsIOArtifact.  # noqa: E501


        :return: The producer of this InputOutputsIOArtifact.  # noqa: E501
        :rtype: InputOutputsIOProducer
        """
        return self._producer

    @producer.setter
    def producer(self, producer):
        """Sets the producer of this InputOutputsIOArtifact.


        :param producer: The producer of this InputOutputsIOArtifact.  # noqa: E501
        :type producer: InputOutputsIOProducer
        """

        self._producer = producer

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InputOutputsIOArtifact):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InputOutputsIOArtifact):
            return True

        return self.to_dict() != other.to_dict()
