# coding: utf-8

"""
    Kubeflow Pipelines API

    This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.

    Contact: kubeflow-pipelines@google.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kfp_server_api.configuration import Configuration


class InputOutputsIOProducer(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'task_name': 'str',
        'key': 'str'
    }

    attribute_map = {
        'task_name': 'task_name',
        'key': 'key'
    }

    def __init__(self, task_name=None, key=None, local_vars_configuration=None):  # noqa: E501
        """InputOutputsIOProducer - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._task_name = None
        self._key = None
        self.discriminator = None

        if task_name is not None:
            self.task_name = task_name
        if key is not None:
            self.key = key

    @property
    def task_name(self):
        """Gets the task_name of this InputOutputsIOProducer.  # noqa: E501


        :return: The task_name of this InputOutputsIOProducer.  # noqa: E501
        :rtype: str
        """
        return self._task_name

    @task_name.setter
    def task_name(self, task_name):
        """Sets the task_name of this InputOutputsIOProducer.


        :param task_name: The task_name of this InputOutputsIOProducer.  # noqa: E501
        :type task_name: str
        """

        self._task_name = task_name

    @property
    def key(self):
        """Gets the key of this InputOutputsIOProducer.  # noqa: E501

        This would be the equivalent of output_parameter_key from the upstream task when it's a parameter input, or output_artifact_key when it is an Artifact.  # noqa: E501

        :return: The key of this InputOutputsIOProducer.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this InputOutputsIOProducer.

        This would be the equivalent of output_parameter_key from the upstream task when it's a parameter input, or output_artifact_key when it is an Artifact.  # noqa: E501

        :param key: The key of this InputOutputsIOProducer.  # noqa: E501
        :type key: str
        """

        self._key = key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InputOutputsIOProducer):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InputOutputsIOProducer):
            return True

        return self.to_dict() != other.to_dict()
