# coding: utf-8

"""
    Kubeflow Pipelines API

    This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.

    Contact: kubeflow-pipelines@google.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kfp_server_api.configuration import Configuration


class V2beta1ArtifactTask(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'artifact_id': 'str',
        'run_id': 'str',
        'task_id': 'str',
        'type': 'V2beta1ArtifactTaskType',
        'producer_task_name': 'str',
        'producer_key': 'str',
        'artifact_key': 'str'
    }

    attribute_map = {
        'id': 'id',
        'artifact_id': 'artifact_id',
        'run_id': 'run_id',
        'task_id': 'task_id',
        'type': 'type',
        'producer_task_name': 'producer_task_name',
        'producer_key': 'producer_key',
        'artifact_key': 'artifact_key'
    }

    def __init__(self, id=None, artifact_id=None, run_id=None, task_id=None, type=None, producer_task_name=None, producer_key=None, artifact_key=None, local_vars_configuration=None):  # noqa: E501
        """V2beta1ArtifactTask - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._artifact_id = None
        self._run_id = None
        self._task_id = None
        self._type = None
        self._producer_task_name = None
        self._producer_key = None
        self._artifact_key = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if artifact_id is not None:
            self.artifact_id = artifact_id
        if run_id is not None:
            self.run_id = run_id
        if task_id is not None:
            self.task_id = task_id
        if type is not None:
            self.type = type
        if producer_task_name is not None:
            self.producer_task_name = producer_task_name
        if producer_key is not None:
            self.producer_key = producer_key
        if artifact_key is not None:
            self.artifact_key = artifact_key

    @property
    def id(self):
        """Gets the id of this V2beta1ArtifactTask.  # noqa: E501

        Output only. The unique server generated id of the ArtifactTask.  # noqa: E501

        :return: The id of this V2beta1ArtifactTask.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this V2beta1ArtifactTask.

        Output only. The unique server generated id of the ArtifactTask.  # noqa: E501

        :param id: The id of this V2beta1ArtifactTask.  # noqa: E501
        :type id: str
        """

        self._id = id

    @property
    def artifact_id(self):
        """Gets the artifact_id of this V2beta1ArtifactTask.  # noqa: E501


        :return: The artifact_id of this V2beta1ArtifactTask.  # noqa: E501
        :rtype: str
        """
        return self._artifact_id

    @artifact_id.setter
    def artifact_id(self, artifact_id):
        """Sets the artifact_id of this V2beta1ArtifactTask.


        :param artifact_id: The artifact_id of this V2beta1ArtifactTask.  # noqa: E501
        :type artifact_id: str
        """

        self._artifact_id = artifact_id

    @property
    def run_id(self):
        """Gets the run_id of this V2beta1ArtifactTask.  # noqa: E501


        :return: The run_id of this V2beta1ArtifactTask.  # noqa: E501
        :rtype: str
        """
        return self._run_id

    @run_id.setter
    def run_id(self, run_id):
        """Sets the run_id of this V2beta1ArtifactTask.


        :param run_id: The run_id of this V2beta1ArtifactTask.  # noqa: E501
        :type run_id: str
        """

        self._run_id = run_id

    @property
    def task_id(self):
        """Gets the task_id of this V2beta1ArtifactTask.  # noqa: E501


        :return: The task_id of this V2beta1ArtifactTask.  # noqa: E501
        :rtype: str
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id):
        """Sets the task_id of this V2beta1ArtifactTask.


        :param task_id: The task_id of this V2beta1ArtifactTask.  # noqa: E501
        :type task_id: str
        """

        self._task_id = task_id

    @property
    def type(self):
        """Gets the type of this V2beta1ArtifactTask.  # noqa: E501


        :return: The type of this V2beta1ArtifactTask.  # noqa: E501
        :rtype: V2beta1ArtifactTaskType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this V2beta1ArtifactTask.


        :param type: The type of this V2beta1ArtifactTask.  # noqa: E501
        :type type: V2beta1ArtifactTaskType
        """

        self._type = type

    @property
    def producer_task_name(self):
        """Gets the producer_task_name of this V2beta1ArtifactTask.  # noqa: E501

        The task that produced this artifact For example in the case of a pipeline channel that is an output artifact you might have as input something like the following in the IR:   taskOutputArtifact:     outputArtifactKey: output_dataset     producerTask: create-dataset These fields are used to track this lineage.  For outputs, the producer task is the component name of the task that produced the artifact.  # noqa: E501

        :return: The producer_task_name of this V2beta1ArtifactTask.  # noqa: E501
        :rtype: str
        """
        return self._producer_task_name

    @producer_task_name.setter
    def producer_task_name(self, producer_task_name):
        """Sets the producer_task_name of this V2beta1ArtifactTask.

        The task that produced this artifact For example in the case of a pipeline channel that is an output artifact you might have as input something like the following in the IR:   taskOutputArtifact:     outputArtifactKey: output_dataset     producerTask: create-dataset These fields are used to track this lineage.  For outputs, the producer task is the component name of the task that produced the artifact.  # noqa: E501

        :param producer_task_name: The producer_task_name of this V2beta1ArtifactTask.  # noqa: E501
        :type producer_task_name: str
        """

        self._producer_task_name = producer_task_name

    @property
    def producer_key(self):
        """Gets the producer_key of this V2beta1ArtifactTask.  # noqa: E501

        For outputs, the key is the name of the parameter in the component spec (found in OutputDefinitions) used to output the artifact.  # noqa: E501

        :return: The producer_key of this V2beta1ArtifactTask.  # noqa: E501
        :rtype: str
        """
        return self._producer_key

    @producer_key.setter
    def producer_key(self, producer_key):
        """Sets the producer_key of this V2beta1ArtifactTask.

        For outputs, the key is the name of the parameter in the component spec (found in OutputDefinitions) used to output the artifact.  # noqa: E501

        :param producer_key: The producer_key of this V2beta1ArtifactTask.  # noqa: E501
        :type producer_key: str
        """

        self._producer_key = producer_key

    @property
    def artifact_key(self):
        """Gets the artifact_key of this V2beta1ArtifactTask.  # noqa: E501

        The parameter name for the input/output artifact This maybe the same as the Artifact name if the artifact name is not specified. It is used to resolve artifact pipeline channels.  # noqa: E501

        :return: The artifact_key of this V2beta1ArtifactTask.  # noqa: E501
        :rtype: str
        """
        return self._artifact_key

    @artifact_key.setter
    def artifact_key(self, artifact_key):
        """Sets the artifact_key of this V2beta1ArtifactTask.

        The parameter name for the input/output artifact This maybe the same as the Artifact name if the artifact name is not specified. It is used to resolve artifact pipeline channels.  # noqa: E501

        :param artifact_key: The artifact_key of this V2beta1ArtifactTask.  # noqa: E501
        :type artifact_key: str
        """

        self._artifact_key = artifact_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2beta1ArtifactTask):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V2beta1ArtifactTask):
            return True

        return self.to_dict() != other.to_dict()
