// Copyright 2025 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: backend/api/v2beta1/artifact.proto

package go_client

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Describes the I/O relationship between
// this Artifact and Task
type ArtifactTaskType int32

const (
	ArtifactTaskType_INPUT  ArtifactTaskType = 0
	ArtifactTaskType_OUTPUT ArtifactTaskType = 1
)

// Enum value maps for ArtifactTaskType.
var (
	ArtifactTaskType_name = map[int32]string{
		0: "INPUT",
		1: "OUTPUT",
	}
	ArtifactTaskType_value = map[string]int32{
		"INPUT":  0,
		"OUTPUT": 1,
	}
)

func (x ArtifactTaskType) Enum() *ArtifactTaskType {
	p := new(ArtifactTaskType)
	*p = x
	return p
}

func (x ArtifactTaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactTaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_backend_api_v2beta1_artifact_proto_enumTypes[0].Descriptor()
}

func (ArtifactTaskType) Type() protoreflect.EnumType {
	return &file_backend_api_v2beta1_artifact_proto_enumTypes[0]
}

func (x ArtifactTaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactTaskType.Descriptor instead.
func (ArtifactTaskType) EnumDescriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{0}
}

type Artifact_ArtifactType int32

const (
	// default; treated as "not set"
	// reject if unset.
	Artifact_TYPE_UNSPECIFIED           Artifact_ArtifactType = 0
	Artifact_Artifact                   Artifact_ArtifactType = 1
	Artifact_Model                      Artifact_ArtifactType = 2
	Artifact_Dataset                    Artifact_ArtifactType = 3
	Artifact_HTML                       Artifact_ArtifactType = 4
	Artifact_Markdown                   Artifact_ArtifactType = 5
	Artifact_Metric                     Artifact_ArtifactType = 6
	Artifact_ClassificationMetric       Artifact_ArtifactType = 7
	Artifact_SlicedClassificationMetric Artifact_ArtifactType = 8
)

// Enum value maps for Artifact_ArtifactType.
var (
	Artifact_ArtifactType_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "Artifact",
		2: "Model",
		3: "Dataset",
		4: "HTML",
		5: "Markdown",
		6: "Metric",
		7: "ClassificationMetric",
		8: "SlicedClassificationMetric",
	}
	Artifact_ArtifactType_value = map[string]int32{
		"TYPE_UNSPECIFIED":           0,
		"Artifact":                   1,
		"Model":                      2,
		"Dataset":                    3,
		"HTML":                       4,
		"Markdown":                   5,
		"Metric":                     6,
		"ClassificationMetric":       7,
		"SlicedClassificationMetric": 8,
	}
)

func (x Artifact_ArtifactType) Enum() *Artifact_ArtifactType {
	p := new(Artifact_ArtifactType)
	*p = x
	return p
}

func (x Artifact_ArtifactType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Artifact_ArtifactType) Descriptor() protoreflect.EnumDescriptor {
	return file_backend_api_v2beta1_artifact_proto_enumTypes[1].Descriptor()
}

func (Artifact_ArtifactType) Type() protoreflect.EnumType {
	return &file_backend_api_v2beta1_artifact_proto_enumTypes[1]
}

func (x Artifact_ArtifactType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Artifact_ArtifactType.Descriptor instead.
func (Artifact_ArtifactType) EnumDescriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{8, 0}
}

type CreateArtifactRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The artifact to create.
	Artifact *Artifact `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	// An artifact is always created in the context of a
	// run.
	RunId            string           `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TaskId           string           `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type             ArtifactTaskType `protobuf:"varint,4,opt,name=type,proto3,enum=kubeflow.pipelines.backend.api.v2beta1.ArtifactTaskType" json:"type,omitempty"`
	ProducerTaskName string           `protobuf:"bytes,5,opt,name=producer_task_name,json=producerTaskName,proto3" json:"producer_task_name,omitempty"`
	ProducerKey      string           `protobuf:"bytes,6,opt,name=producer_key,json=producerKey,proto3" json:"producer_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateArtifactRequest) Reset() {
	*x = CreateArtifactRequest{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArtifactRequest) ProtoMessage() {}

func (x *CreateArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArtifactRequest.ProtoReflect.Descriptor instead.
func (*CreateArtifactRequest) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{0}
}

func (x *CreateArtifactRequest) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *CreateArtifactRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CreateArtifactRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateArtifactRequest) GetType() ArtifactTaskType {
	if x != nil {
		return x.Type
	}
	return ArtifactTaskType_INPUT
}

func (x *CreateArtifactRequest) GetProducerTaskName() string {
	if x != nil {
		return x.ProducerTaskName
	}
	return ""
}

func (x *CreateArtifactRequest) GetProducerKey() string {
	if x != nil {
		return x.ProducerKey
	}
	return ""
}

type GetArtifactRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The ID of the artifact to be retrieved.
	ArtifactId    string `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactRequest) Reset() {
	*x = GetArtifactRequest{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactRequest) ProtoMessage() {}

func (x *GetArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactRequest.ProtoReflect.Descriptor instead.
func (*GetArtifactRequest) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{1}
}

func (x *GetArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

type ListArtifactRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional input. Namespace for the artifacts.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// A page token to request the results page.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// The number of artifacts to be listed per page. If there are more artifacts
	// than this number, the response message will contain a valid value in the
	// nextPageToken field.
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Sorting order in form of "field_name", "field_name asc" or "field_name desc".
	// Ascending by default.
	SortBy string `protobuf:"bytes,4,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	// A url-encoded, JSON-serialized filter protocol buffer (see
	// [filter.proto](https://github.com/kubeflow/artifacts/blob/master/backend/api/filter.proto)).
	Filter        string `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactRequest) Reset() {
	*x = ListArtifactRequest{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactRequest) ProtoMessage() {}

func (x *ListArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactRequest.ProtoReflect.Descriptor instead.
func (*ListArtifactRequest) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{2}
}

func (x *ListArtifactRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListArtifactRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListArtifactRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListArtifactRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListArtifactRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListArtifactResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of artifacts returned.
	Artifacts []*Artifact `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	// The total number of artifacts available. This field is not always populated.
	TotalSize int32 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	// A token to retrieve the next page of results, or empty if there are no
	// more results in the list.
	NextPageToken string `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactResponse) Reset() {
	*x = ListArtifactResponse{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactResponse) ProtoMessage() {}

func (x *ListArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactResponse.ProtoReflect.Descriptor instead.
func (*ListArtifactResponse) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{3}
}

func (x *ListArtifactResponse) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *ListArtifactResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ListArtifactResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// The fields here work the same as previous backend api calls
type ListArtifactTasksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional, filter artifact task by a set of task_ids
	// We can also likely just rely on filter for this and omit this field
	TaskIds []string `protobuf:"bytes,1,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	// Optional, filter artifact task by a set of run_ids
	RunIds []string `protobuf:"bytes,2,rep,name=run_ids,json=runIds,proto3" json:"run_ids,omitempty"`
	// Optional, filter artifact task by a set of artifact_ids
	// We can also likely just rely on filter for this and omit this field
	ArtifactIds []string `protobuf:"bytes,3,rep,name=artifact_ids,json=artifactIds,proto3" json:"artifact_ids,omitempty"`
	// Optional. Only list artifact tasks that have artifacts of this type.
	Type          ArtifactTaskType `protobuf:"varint,4,opt,name=type,proto3,enum=kubeflow.pipelines.backend.api.v2beta1.ArtifactTaskType" json:"type,omitempty"`
	PageToken     string           `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize      int32            `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string           `protobuf:"bytes,7,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	Filter        string           `protobuf:"bytes,8,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactTasksRequest) Reset() {
	*x = ListArtifactTasksRequest{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactTasksRequest) ProtoMessage() {}

func (x *ListArtifactTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactTasksRequest.ProtoReflect.Descriptor instead.
func (*ListArtifactTasksRequest) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{4}
}

func (x *ListArtifactTasksRequest) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

func (x *ListArtifactTasksRequest) GetRunIds() []string {
	if x != nil {
		return x.RunIds
	}
	return nil
}

func (x *ListArtifactTasksRequest) GetArtifactIds() []string {
	if x != nil {
		return x.ArtifactIds
	}
	return nil
}

func (x *ListArtifactTasksRequest) GetType() ArtifactTaskType {
	if x != nil {
		return x.Type
	}
	return ArtifactTaskType_INPUT
}

func (x *ListArtifactTasksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListArtifactTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListArtifactTasksRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListArtifactTasksRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListArtifactTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactTasks []*ArtifactTask        `protobuf:"bytes,1,rep,name=artifact_tasks,json=artifactTasks,proto3" json:"artifact_tasks,omitempty"`
	TotalSize     int32                  `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	NextPageToken string                 `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactTasksResponse) Reset() {
	*x = ListArtifactTasksResponse{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactTasksResponse) ProtoMessage() {}

func (x *ListArtifactTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactTasksResponse.ProtoReflect.Descriptor instead.
func (*ListArtifactTasksResponse) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{5}
}

func (x *ListArtifactTasksResponse) GetArtifactTasks() []*ArtifactTask {
	if x != nil {
		return x.ArtifactTasks
	}
	return nil
}

func (x *ListArtifactTasksResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ListArtifactTasksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request to create an artifact-task relationship
type CreateArtifactTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The artifact-task relationship to create.
	ArtifactTask  *ArtifactTask `protobuf:"bytes,1,opt,name=artifact_task,json=artifactTask,proto3" json:"artifact_task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArtifactTaskRequest) Reset() {
	*x = CreateArtifactTaskRequest{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArtifactTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArtifactTaskRequest) ProtoMessage() {}

func (x *CreateArtifactTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArtifactTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateArtifactTaskRequest) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{6}
}

func (x *CreateArtifactTaskRequest) GetArtifactTask() *ArtifactTask {
	if x != nil {
		return x.ArtifactTask
	}
	return nil
}

type ArtifactTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. The unique server generated id of the ArtifactTask.
	Id         string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ArtifactId string           `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	RunId      string           `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TaskId     string           `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type       ArtifactTaskType `protobuf:"varint,5,opt,name=type,proto3,enum=kubeflow.pipelines.backend.api.v2beta1.ArtifactTaskType" json:"type,omitempty"`
	// The task that produced this artifact
	// For example in the case of a pipeline channel
	// that is an output artifact you might have as
	// input something like the following in the IR:
	//
	//	taskOutputArtifact:
	//	  outputArtifactKey: output_dataset
	//	  producerTask: create-dataset
	//
	// These fields are used to track this lineage.
	//
	// For outputs, the producer task is the component name
	// of the task that produced the artifact.
	ProducerTaskName string `protobuf:"bytes,6,opt,name=producer_task_name,json=producerTaskName,proto3" json:"producer_task_name,omitempty"`
	// The key is often the parameter name used
	// as input/output on the component, but
	// can also take on the value of of other values.
	// For example:
	//   - "param-#" when using parameters in a ParallelFor
	//   - "Output" when using Pythonic Artifacts
	//
	// For outputs, the key is the name of the parameter
	// in the component spec (found in OutputDefinitions)
	// used to output the artifact.
	ProducerKey string `protobuf:"bytes,7,opt,name=producer_key,json=producerKey,proto3" json:"producer_key,omitempty"`
	// The parameter name for the input/output artifact
	// This maybe the same as the Artifact name if the
	// artifact name is not specified. It is used to
	// resolve artifact pipeline channels.
	ArtifactKey   string `protobuf:"bytes,8,opt,name=artifact_key,json=artifactKey,proto3" json:"artifact_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactTask) Reset() {
	*x = ArtifactTask{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactTask) ProtoMessage() {}

func (x *ArtifactTask) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactTask.ProtoReflect.Descriptor instead.
func (*ArtifactTask) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{7}
}

func (x *ArtifactTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArtifactTask) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ArtifactTask) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ArtifactTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ArtifactTask) GetType() ArtifactTaskType {
	if x != nil {
		return x.Type
	}
	return ArtifactTaskType_INPUT
}

func (x *ArtifactTask) GetProducerTaskName() string {
	if x != nil {
		return x.ProducerTaskName
	}
	return ""
}

func (x *ArtifactTask) GetProducerKey() string {
	if x != nil {
		return x.ProducerKey
	}
	return ""
}

func (x *ArtifactTask) GetArtifactKey() string {
	if x != nil {
		return x.ArtifactKey
	}
	return ""
}

// Note to be confused with RuntimeArtifact in pipelinespec
type Artifact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. The unique server generated id of the artifact.
	// Note: Updated id name to be consistent with other api naming patterns (with prefix)
	ArtifactId string `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	// Required. The client provided name of the artifact.
	// Note: it seems in MLMD when name was set, it had to be unique for that type_id
	// this restriction is removed here
	// If this is a "Metric" artifact, the name of the metric
	// is treated as the Key in its K/V pair.
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Required. The name of an ArtifactType. E.g. Dataset
	Type Artifact_ArtifactType `protobuf:"varint,4,opt,name=type,proto3,enum=kubeflow.pipelines.backend.api.v2beta1.Artifact_ArtifactType" json:"type,omitempty"`
	// The uniform resource identifier of the physical artifact.
	// May be empty if there is no physical artifact.
	Uri *string `protobuf:"bytes,5,opt,name=uri,proto3,oneof" json:"uri,omitempty"`
	// Optional. User provided custom properties which are not defined by its type.
	Metadata map[string]*structpb.Value `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Used primarily for metrics
	NumberValue *float64 `protobuf:"fixed64,7,opt,name=number_value,json=numberValue,proto3,oneof" json:"number_value,omitempty"`
	// Output only. Create time of the artifact in millisecond since epoch.
	// Note: The type and name is updated from mlmd artifact to be consistent with other backend apis.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Namespace     string                 `protobuf:"bytes,9,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_v2beta1_artifact_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_backend_api_v2beta1_artifact_proto_rawDescGZIP(), []int{8}
}

func (x *Artifact) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artifact) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Artifact) GetType() Artifact_ArtifactType {
	if x != nil {
		return x.Type
	}
	return Artifact_TYPE_UNSPECIFIED
}

func (x *Artifact) GetUri() string {
	if x != nil && x.Uri != nil {
		return *x.Uri
	}
	return ""
}

func (x *Artifact) GetMetadata() map[string]*structpb.Value {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Artifact) GetNumberValue() float64 {
	if x != nil && x.NumberValue != nil {
		return *x.NumberValue
	}
	return 0
}

func (x *Artifact) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Artifact) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

var File_backend_api_v2beta1_artifact_proto protoreflect.FileDescriptor

const file_backend_api_v2beta1_artifact_proto_rawDesc = "" +
	"\n" +
	"\"backend/api/v2beta1/artifact.proto\x12&kubeflow.pipelines.backend.api.v2beta1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xb4\x02\n" +
	"\x15CreateArtifactRequest\x12L\n" +
	"\bartifact\x18\x01 \x01(\v20.kubeflow.pipelines.backend.api.v2beta1.ArtifactR\bartifact\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12L\n" +
	"\x04type\x18\x04 \x01(\x0e28.kubeflow.pipelines.backend.api.v2beta1.ArtifactTaskTypeR\x04type\x12,\n" +
	"\x12producer_task_name\x18\x05 \x01(\tR\x10producerTaskName\x12!\n" +
	"\fproducer_key\x18\x06 \x01(\tR\vproducerKey\"5\n" +
	"\x12GetArtifactRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\"\xa0\x01\n" +
	"\x13ListArtifactRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x04 \x01(\tR\x06sortBy\x12\x16\n" +
	"\x06filter\x18\x05 \x01(\tR\x06filter\"\xad\x01\n" +
	"\x14ListArtifactResponse\x12N\n" +
	"\tartifacts\x18\x01 \x03(\v20.kubeflow.pipelines.backend.api.v2beta1.ArtifactR\tartifacts\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x05R\ttotalSize\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"\xac\x02\n" +
	"\x18ListArtifactTasksRequest\x12\x19\n" +
	"\btask_ids\x18\x01 \x03(\tR\ataskIds\x12\x17\n" +
	"\arun_ids\x18\x02 \x03(\tR\x06runIds\x12!\n" +
	"\fartifact_ids\x18\x03 \x03(\tR\vartifactIds\x12L\n" +
	"\x04type\x18\x04 \x01(\x0e28.kubeflow.pipelines.backend.api.v2beta1.ArtifactTaskTypeR\x04type\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\a \x01(\tR\x06sortBy\x12\x16\n" +
	"\x06filter\x18\b \x01(\tR\x06filter\"\xbf\x01\n" +
	"\x19ListArtifactTasksResponse\x12[\n" +
	"\x0eartifact_tasks\x18\x01 \x03(\v24.kubeflow.pipelines.backend.api.v2beta1.ArtifactTaskR\rartifactTasks\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x05R\ttotalSize\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"v\n" +
	"\x19CreateArtifactTaskRequest\x12Y\n" +
	"\rartifact_task\x18\x01 \x01(\v24.kubeflow.pipelines.backend.api.v2beta1.ArtifactTaskR\fartifactTask\"\xb1\x02\n" +
	"\fArtifactTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12L\n" +
	"\x04type\x18\x05 \x01(\x0e28.kubeflow.pipelines.backend.api.v2beta1.ArtifactTaskTypeR\x04type\x12,\n" +
	"\x12producer_task_name\x18\x06 \x01(\tR\x10producerTaskName\x12!\n" +
	"\fproducer_key\x18\a \x01(\tR\vproducerKey\x12!\n" +
	"\fartifact_key\x18\b \x01(\tR\vartifactKey\"\xc1\x05\n" +
	"\bArtifact\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12Q\n" +
	"\x04type\x18\x04 \x01(\x0e2=.kubeflow.pipelines.backend.api.v2beta1.Artifact.ArtifactTypeR\x04type\x12\x15\n" +
	"\x03uri\x18\x05 \x01(\tH\x00R\x03uri\x88\x01\x01\x12Z\n" +
	"\bmetadata\x18\x06 \x03(\v2>.kubeflow.pipelines.backend.api.v2beta1.Artifact.MetadataEntryR\bmetadata\x12&\n" +
	"\fnumber_value\x18\a \x01(\x01H\x01R\vnumberValue\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1c\n" +
	"\tnamespace\x18\t \x01(\tR\tnamespace\x1aS\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xa8\x01\n" +
	"\fArtifactType\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bArtifact\x10\x01\x12\t\n" +
	"\x05Model\x10\x02\x12\v\n" +
	"\aDataset\x10\x03\x12\b\n" +
	"\x04HTML\x10\x04\x12\f\n" +
	"\bMarkdown\x10\x05\x12\n" +
	"\n" +
	"\x06Metric\x10\x06\x12\x18\n" +
	"\x14ClassificationMetric\x10\a\x12\x1e\n" +
	"\x1aSlicedClassificationMetric\x10\bB\x06\n" +
	"\x04_uriB\x0f\n" +
	"\r_number_value*)\n" +
	"\x10ArtifactTaskType\x12\t\n" +
	"\x05INPUT\x10\x00\x12\n" +
	"\n" +
	"\x06OUTPUT\x10\x012\xba\x0f\n" +
	"\x0fArtifactService\x12\x84\x02\n" +
	"\rListArtifacts\x12;.kubeflow.pipelines.backend.api.v2beta1.ListArtifactRequest\x1a<.kubeflow.pipelines.backend.api.v2beta1.ListArtifactResponse\"x\x92AV\n" +
	"\x0fArtifactService\x123Finds all artifacts within the specified namespace.*\x0elist_artifacts\x82\xd3\xe4\x93\x02\x19\x12\x17/apis/v2beta1/artifacts\x12\xee\x01\n" +
	"\vGetArtifact\x12:.kubeflow.pipelines.backend.api.v2beta1.GetArtifactRequest\x1a0.kubeflow.pipelines.backend.api.v2beta1.Artifact\"q\x92AA\n" +
	"\x0fArtifactService\x12 Finds a specific Artifact by ID.*\fget_artifact\x82\xd3\xe4\x93\x02'\x12%/apis/v2beta1/artifacts/{artifact_id}\x12\x8b\x02\n" +
	"\x11ListArtifactTasks\x12@.kubeflow.pipelines.backend.api.v2beta1.ListArtifactTasksRequest\x1aA.kubeflow.pipelines.backend.api.v2beta1.ListArtifactTasksResponse\"q\x92AJ\n" +
	"\x0fArtifactService\x12\"Lists artifact-task relationships.*\x13list_artifact_tasks\x82\xd3\xe4\x93\x02\x1e\x12\x1c/apis/v2beta1/artifact_tasks\x12\x88\x02\n" +
	"\x12CreateArtifactTask\x12A.kubeflow.pipelines.backend.api.v2beta1.CreateArtifactTaskRequest\x1a4.kubeflow.pipelines.backend.api.v2beta1.ArtifactTask\"y\x92AO\n" +
	"\x0fArtifactService\x12&Creates an artifact-task relationship.*\x14create_artifact_task\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/apis/v2beta1/artifact_tasks\x12\xe3\x01\n" +
	"\x0eCreateArtifact\x12=.kubeflow.pipelines.backend.api.v2beta1.CreateArtifactRequest\x1a0.kubeflow.pipelines.backend.api.v2beta1.Artifact\"`\x92A;\n" +
	"\x0fArtifactService\x12\x17Creates a new artifact.*\x0fcreate_artifact\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/apis/v2beta1/artifacts\x12\xe2\x01\n" +
	"\tLogMetric\x12=.kubeflow.pipelines.backend.api.v2beta1.CreateArtifactRequest\x1a0.kubeflow.pipelines.backend.api.v2beta1.Artifact\"d\x92AA\n" +
	"\x0fArtifactService\x12\"Logs a metric for a specific task.*\n" +
	"log_metric\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/apis/v2beta1/metrics\x12\xea\x01\n" +
	"\tGetMetric\x12:.kubeflow.pipelines.backend.api.v2beta1.GetArtifactRequest\x1a0.kubeflow.pipelines.backend.api.v2beta1.Artifact\"o\x92AA\n" +
	"\x0fArtifactService\x12\"Gets a metric by task ID and name.*\n" +
	"get_metric\x82\xd3\xe4\x93\x02%\x12#/apis/v2beta1/metrics/{artifact_id}\x12\xdd\x01\n" +
	"\vListMetrics\x12;.kubeflow.pipelines.backend.api.v2beta1.ListArtifactRequest\x1a<.kubeflow.pipelines.backend.api.v2beta1.ListArtifactResponse\"S\x92A3\n" +
	"\x0fArtifactService\x12\x12Lists all metrics.*\flist_metrics\x82\xd3\xe4\x93\x02\x17\x12\x15/apis/v2beta1/metricsB\x8a\x01\x92AJ*\x02\x01\x02R#\n" +
	"\adefault\x12\x18\x12\x16\n" +
	"\x14\x1a\x12.google.rpc.StatusZ\x1f\n" +
	"\x1d\n" +
	"\x06Bearer\x12\x13\b\x02\x1a\rAuthorization \x02Z;github.com/kubeflow/pipelines/backend/api/v2beta1/go_clientb\x06proto3"

var (
	file_backend_api_v2beta1_artifact_proto_rawDescOnce sync.Once
	file_backend_api_v2beta1_artifact_proto_rawDescData []byte
)

func file_backend_api_v2beta1_artifact_proto_rawDescGZIP() []byte {
	file_backend_api_v2beta1_artifact_proto_rawDescOnce.Do(func() {
		file_backend_api_v2beta1_artifact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_api_v2beta1_artifact_proto_rawDesc), len(file_backend_api_v2beta1_artifact_proto_rawDesc)))
	})
	return file_backend_api_v2beta1_artifact_proto_rawDescData
}

var file_backend_api_v2beta1_artifact_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_backend_api_v2beta1_artifact_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_backend_api_v2beta1_artifact_proto_goTypes = []any{
	(ArtifactTaskType)(0),             // 0: kubeflow.pipelines.backend.api.v2beta1.ArtifactTaskType
	(Artifact_ArtifactType)(0),        // 1: kubeflow.pipelines.backend.api.v2beta1.Artifact.ArtifactType
	(*CreateArtifactRequest)(nil),     // 2: kubeflow.pipelines.backend.api.v2beta1.CreateArtifactRequest
	(*GetArtifactRequest)(nil),        // 3: kubeflow.pipelines.backend.api.v2beta1.GetArtifactRequest
	(*ListArtifactRequest)(nil),       // 4: kubeflow.pipelines.backend.api.v2beta1.ListArtifactRequest
	(*ListArtifactResponse)(nil),      // 5: kubeflow.pipelines.backend.api.v2beta1.ListArtifactResponse
	(*ListArtifactTasksRequest)(nil),  // 6: kubeflow.pipelines.backend.api.v2beta1.ListArtifactTasksRequest
	(*ListArtifactTasksResponse)(nil), // 7: kubeflow.pipelines.backend.api.v2beta1.ListArtifactTasksResponse
	(*CreateArtifactTaskRequest)(nil), // 8: kubeflow.pipelines.backend.api.v2beta1.CreateArtifactTaskRequest
	(*ArtifactTask)(nil),              // 9: kubeflow.pipelines.backend.api.v2beta1.ArtifactTask
	(*Artifact)(nil),                  // 10: kubeflow.pipelines.backend.api.v2beta1.Artifact
	nil,                               // 11: kubeflow.pipelines.backend.api.v2beta1.Artifact.MetadataEntry
	(*timestamppb.Timestamp)(nil),     // 12: google.protobuf.Timestamp
	(*structpb.Value)(nil),            // 13: google.protobuf.Value
}
var file_backend_api_v2beta1_artifact_proto_depIdxs = []int32{
	10, // 0: kubeflow.pipelines.backend.api.v2beta1.CreateArtifactRequest.artifact:type_name -> kubeflow.pipelines.backend.api.v2beta1.Artifact
	0,  // 1: kubeflow.pipelines.backend.api.v2beta1.CreateArtifactRequest.type:type_name -> kubeflow.pipelines.backend.api.v2beta1.ArtifactTaskType
	10, // 2: kubeflow.pipelines.backend.api.v2beta1.ListArtifactResponse.artifacts:type_name -> kubeflow.pipelines.backend.api.v2beta1.Artifact
	0,  // 3: kubeflow.pipelines.backend.api.v2beta1.ListArtifactTasksRequest.type:type_name -> kubeflow.pipelines.backend.api.v2beta1.ArtifactTaskType
	9,  // 4: kubeflow.pipelines.backend.api.v2beta1.ListArtifactTasksResponse.artifact_tasks:type_name -> kubeflow.pipelines.backend.api.v2beta1.ArtifactTask
	9,  // 5: kubeflow.pipelines.backend.api.v2beta1.CreateArtifactTaskRequest.artifact_task:type_name -> kubeflow.pipelines.backend.api.v2beta1.ArtifactTask
	0,  // 6: kubeflow.pipelines.backend.api.v2beta1.ArtifactTask.type:type_name -> kubeflow.pipelines.backend.api.v2beta1.ArtifactTaskType
	1,  // 7: kubeflow.pipelines.backend.api.v2beta1.Artifact.type:type_name -> kubeflow.pipelines.backend.api.v2beta1.Artifact.ArtifactType
	11, // 8: kubeflow.pipelines.backend.api.v2beta1.Artifact.metadata:type_name -> kubeflow.pipelines.backend.api.v2beta1.Artifact.MetadataEntry
	12, // 9: kubeflow.pipelines.backend.api.v2beta1.Artifact.created_at:type_name -> google.protobuf.Timestamp
	13, // 10: kubeflow.pipelines.backend.api.v2beta1.Artifact.MetadataEntry.value:type_name -> google.protobuf.Value
	4,  // 11: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.ListArtifacts:input_type -> kubeflow.pipelines.backend.api.v2beta1.ListArtifactRequest
	3,  // 12: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.GetArtifact:input_type -> kubeflow.pipelines.backend.api.v2beta1.GetArtifactRequest
	6,  // 13: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.ListArtifactTasks:input_type -> kubeflow.pipelines.backend.api.v2beta1.ListArtifactTasksRequest
	8,  // 14: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.CreateArtifactTask:input_type -> kubeflow.pipelines.backend.api.v2beta1.CreateArtifactTaskRequest
	2,  // 15: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.CreateArtifact:input_type -> kubeflow.pipelines.backend.api.v2beta1.CreateArtifactRequest
	2,  // 16: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.LogMetric:input_type -> kubeflow.pipelines.backend.api.v2beta1.CreateArtifactRequest
	3,  // 17: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.GetMetric:input_type -> kubeflow.pipelines.backend.api.v2beta1.GetArtifactRequest
	4,  // 18: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.ListMetrics:input_type -> kubeflow.pipelines.backend.api.v2beta1.ListArtifactRequest
	5,  // 19: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.ListArtifacts:output_type -> kubeflow.pipelines.backend.api.v2beta1.ListArtifactResponse
	10, // 20: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.GetArtifact:output_type -> kubeflow.pipelines.backend.api.v2beta1.Artifact
	7,  // 21: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.ListArtifactTasks:output_type -> kubeflow.pipelines.backend.api.v2beta1.ListArtifactTasksResponse
	9,  // 22: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.CreateArtifactTask:output_type -> kubeflow.pipelines.backend.api.v2beta1.ArtifactTask
	10, // 23: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.CreateArtifact:output_type -> kubeflow.pipelines.backend.api.v2beta1.Artifact
	10, // 24: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.LogMetric:output_type -> kubeflow.pipelines.backend.api.v2beta1.Artifact
	10, // 25: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.GetMetric:output_type -> kubeflow.pipelines.backend.api.v2beta1.Artifact
	5,  // 26: kubeflow.pipelines.backend.api.v2beta1.ArtifactService.ListMetrics:output_type -> kubeflow.pipelines.backend.api.v2beta1.ListArtifactResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_backend_api_v2beta1_artifact_proto_init() }
func file_backend_api_v2beta1_artifact_proto_init() {
	if File_backend_api_v2beta1_artifact_proto != nil {
		return
	}
	file_backend_api_v2beta1_artifact_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_api_v2beta1_artifact_proto_rawDesc), len(file_backend_api_v2beta1_artifact_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_api_v2beta1_artifact_proto_goTypes,
		DependencyIndexes: file_backend_api_v2beta1_artifact_proto_depIdxs,
		EnumInfos:         file_backend_api_v2beta1_artifact_proto_enumTypes,
		MessageInfos:      file_backend_api_v2beta1_artifact_proto_msgTypes,
	}.Build()
	File_backend_api_v2beta1_artifact_proto = out.File
	file_backend_api_v2beta1_artifact_proto_goTypes = nil
	file_backend_api_v2beta1_artifact_proto_depIdxs = nil
}
