// Code generated by go-swagger; DO NOT EDIT.

package artifact_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// V2beta1IOType  - UNSPECIFIED: For validation
//   - ITERATOR_INPUT: In a for loop task, introduced via ParallelFor, this type
//
// is used to indicate whether this resolved input belongs
// to a parameterIterator or artifactIterator.
//
// swagger:model v2beta1IOType
type V2beta1IOType string

func NewV2beta1IOType(value V2beta1IOType) *V2beta1IOType {
	return &value
}

// Pointer returns a pointer to a freshly-allocated V2beta1IOType.
func (m V2beta1IOType) Pointer() *V2beta1IOType {
	return &m
}

const (

	// V2beta1IOTypeUNSPECIFIED captures enum value "UNSPECIFIED"
	V2beta1IOTypeUNSPECIFIED V2beta1IOType = "UNSPECIFIED"

	// V2beta1IOTypeINPUT captures enum value "INPUT"
	V2beta1IOTypeINPUT V2beta1IOType = "INPUT"

	// V2beta1IOTypeOUTPUT captures enum value "OUTPUT"
	V2beta1IOTypeOUTPUT V2beta1IOType = "OUTPUT"

	// V2beta1IOTypeITERATORINPUT captures enum value "ITERATOR_INPUT"
	V2beta1IOTypeITERATORINPUT V2beta1IOType = "ITERATOR_INPUT"
)

// for schema
var v2beta1IOTypeEnum []interface{}

func init() {
	var res []V2beta1IOType
	if err := json.Unmarshal([]byte(`["UNSPECIFIED","INPUT","OUTPUT","ITERATOR_INPUT"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v2beta1IOTypeEnum = append(v2beta1IOTypeEnum, v)
	}
}

func (m V2beta1IOType) validateV2beta1IOTypeEnum(path, location string, value V2beta1IOType) error {
	if err := validate.EnumCase(path, location, value, v2beta1IOTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this v2beta1 i o type
func (m V2beta1IOType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateV2beta1IOTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this v2beta1 i o type based on context it is used
func (m V2beta1IOType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
