---
# RFE Workflow Configuration for Kubeflow Pipelines
# Based on vTeam RFE system, adapted for KFP ecosystem

rfe_system:
  name: "KFP RFE Workflow System"
  version: "1.0.0"
  description: "AI-powered Request for Enhancement workflow for Kubeflow Pipelines"

# Agent Council Configuration
agent_council:
  enabled: true
  agents:
    - name: "Parker"
      role: "Product Manager"
      enabled: true
      weight: 0.20
    - name: "Archie"
      role: "Architect"
      enabled: true
      weight: 0.20
    - name: "Stella"
      role: "Staff Engineer"
      enabled: true
      weight: 0.15
    - name: "Uma"
      role: "UX Team Lead"
      enabled: true
      weight: 0.10
    - name: "Lee"
      role: "Team Lead"
      enabled: true
      weight: 0.10
    - name: "Neil"
      role: "Test Engineer"
      enabled: true
      weight: 0.15
    - name: "Jack"
      role: "Delivery Owner"
      enabled: true
      weight: 0.10

# Workflow Configuration
workflow:
  timeout_seconds: 3600  # 1 hour default timeout
  max_parallel_agents: 7
  retry_attempts: 3

  phases:
    - name: "Initializing"
      description: "RFE workflow initialization"
      timeout_seconds: 300
    - name: "Ready"
      description: "Ready for agent analysis"
      timeout_seconds: 60
    - name: "Agent_Analysis"
      description: "Agent council analysis in progress"
      timeout_seconds: 1800  # 30 minutes
    - name: "Specification"
      description: "Generating specification document"
      timeout_seconds: 600
    - name: "Planning"
      description: "Generating implementation plan"
      timeout_seconds: 600
    - name: "Tasks_Generation"
      description: "Generating task breakdown"
      timeout_seconds: 600
    - name: "Approved"
      description: "RFE approved for implementation"
    - name: "Rejected"
      description: "RFE rejected or needs revision"
    - name: "Completed"
      description: "RFE workflow completed"

# Approval Criteria
approval:
  minimum_overall_score: 7.0
  required_agent_approvals:
    - "Parker"   # Business value must be positive
    - "Archie"   # Technical feasibility must be confirmed
    - "Stella"   # Implementation must be viable

  minimum_scores:
    business_value: 6.0      # Parker minimum
    technical_feasibility: 7.0  # Archie minimum
    implementation_viability: 6.5  # Stella minimum

  blocking_concerns:
    - "Security vulnerabilities"
    - "Breaking API changes"
    - "Performance regressions"
    - "Incompatible dependencies"
    - "Major architectural changes without consensus"

# KFP-Specific Configuration
kfp_integration:
  supported_component_types:
    - "python_component"
    - "container_component"
    - "pipeline"
    - "notebook_component"
    - "importer"

  repository_patterns:
    umbrella_repos:
      - "https://github.com/kubeflow/pipelines"
      - "https://github.com/kubeflow/pipelines.git"

    supporting_repos:
      - "https://github.com/kubeflow/examples"
      - "https://github.com/kubeflow/kfp-tekton"
      - "https://github.com/kubeflow/training-operator"

  testing_environments:
    - name: "standard"
      description: "Standard Kubernetes cluster"
      required: true
    - name: "openshift"
      description: "OpenShift cluster testing"
      required: true
    - name: "fips"
      description: "FIPS-enabled environment"
      required: false
    - name: "disconnected"
      description: "Disconnected/air-gapped environment"
      required: false
    - name: "multiuser"
      description: "Multi-user KFP deployment"
      required: true

# Document Generation
document_generation:
  templates_path: "templates/"
  output_format: "markdown"

  artifacts:
    spec:
      filename: "spec.md"
      template: "spec_template.md"
      description: "Feature specification document"

    plan:
      filename: "plan.md"
      template: "plan_template.md"
      description: "Implementation plan document"

    tasks:
      filename: "tasks.md"
      template: "tasks_template.md"
      description: "Task breakdown document"

# Integration Settings
integrations:
  git:
    enabled: true
    default_branch: "main"
    commit_message_template: "RFE: {title}\n\n{description}\n\nGenerated by KFP RFE Workflow System"

    pr_settings:
      auto_create: false
      title_template: "RFE: {title}"
      body_template: |
        ## RFE Implementation

        **RFE ID**: {rfe_id}
        **Overall Score**: {overall_score}/10
        **Status**: {decision}

        ### Agent Analysis Summary
        {agent_summary}

        ### Generated Artifacts
        - [x] Specification: {spec_url}
        - [x] Implementation Plan: {plan_url}
        - [x] Task Breakdown: {tasks_url}

        ### Testing Requirements
        - [ ] Unit tests
        - [ ] Integration tests
        - [ ] Performance tests
        - [ ] Security tests

        ---
        Generated by KFP RFE Workflow System

  jira:
    enabled: false  # Optional integration
    project_key: ""
    issue_type: "Epic"

  claude:
    model: "claude-3-5-sonnet-20241022"
    max_tokens: 4096
    temperature: 0.1

    system_prompts:
      business_analysis: |
        You are Parker, a Product Manager analyzing RFE requests for Kubeflow Pipelines.
        Focus on business value, user impact, and strategic alignment.
        Provide scores 1-10 and specific recommendations.

      technical_analysis: |
        You are Archie, a Software Architect analyzing technical feasibility for KFP features.
        Evaluate integration complexity, performance impact, and architectural consistency.
        Consider Argo Workflows integration and Kubernetes-native patterns.

      implementation_analysis: |
        You are Stella, a Staff Engineer evaluating implementation approaches for KFP.
        Assess development complexity, code quality impact, and testing requirements.
        Consider SDK design patterns and backend integration points.

# Security and Compliance
security:
  enable_audit_logging: true
  require_approval_for_breaking_changes: true
  security_review_threshold_score: 8.0

  compliance_checks:
    - "GDPR compliance for user data"
    - "Security scanning for vulnerabilities"
    - "License compatibility verification"
    - "Export control compliance"

# Monitoring and Observability
monitoring:
  metrics:
    enabled: true
    endpoint: "/metrics"

    tracked_metrics:
      - "rfe_workflow_duration_seconds"
      - "rfe_approval_rate"
      - "agent_analysis_duration_seconds"
      - "document_generation_duration_seconds"

  logging:
    level: "INFO"
    format: "json"

    log_events:
      - "rfe_created"
      - "agent_analysis_started"
      - "agent_analysis_completed"
      - "approval_decision_made"
      - "artifacts_generated"
      - "workflow_completed"

# Development and Testing
development:
  mock_mode: false  # Set to true for testing without actual Claude API calls
  debug_logging: false

  test_data:
    sample_rfe_title: "Enhanced XGBoost Component Support"
    sample_rfe_description: "Add comprehensive support for XGBoost components with hyperparameter tuning"
    sample_repo_url: "https://github.com/kubeflow/pipelines.git"