// Code generated by go-swagger; DO NOT EDIT.

package run_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InputOutputsIOProducer input outputs i o producer
//
// swagger:model InputOutputsIOProducer
type InputOutputsIOProducer struct {

	// This would be the equivalent of output_parameter_key from the upstream task
	// when it's a parameter input, or output_artifact_key when it is an Artifact.
	Key string `json:"key,omitempty"`

	// task name
	TaskName string `json:"task_name,omitempty"`
}

// Validate validates this input outputs i o producer
func (m *InputOutputsIOProducer) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this input outputs i o producer based on context it is used
func (m *InputOutputsIOProducer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InputOutputsIOProducer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InputOutputsIOProducer) UnmarshalBinary(b []byte) error {
	var res InputOutputsIOProducer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
