// Code generated by go-swagger; DO NOT EDIT.

package run_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InputOutputsIOArtifact input outputs i o artifact
//
// swagger:model InputOutputsIOArtifact
type InputOutputsIOArtifact struct {

	// This is included on Runtime Tasks when the parameter name is known.
	ParameterName string `json:"parameter_name,omitempty"`

	// Handle Pipeline Channel case.
	Producer *InputOutputsIOProducer `json:"producer,omitempty"`

	// value
	Value *V2beta1Artifact `json:"value,omitempty"`
}

// Validate validates this input outputs i o artifact
func (m *InputOutputsIOArtifact) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProducer(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InputOutputsIOArtifact) validateProducer(formats strfmt.Registry) error {
	if swag.IsZero(m.Producer) { // not required
		return nil
	}

	if m.Producer != nil {
		if err := m.Producer.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("producer")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("producer")
			}
			return err
		}
	}

	return nil
}

func (m *InputOutputsIOArtifact) validateValue(formats strfmt.Registry) error {
	if swag.IsZero(m.Value) { // not required
		return nil
	}

	if m.Value != nil {
		if err := m.Value.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("value")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("value")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this input outputs i o artifact based on the context it is used
func (m *InputOutputsIOArtifact) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateProducer(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateValue(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InputOutputsIOArtifact) contextValidateProducer(ctx context.Context, formats strfmt.Registry) error {

	if m.Producer != nil {

		if swag.IsZero(m.Producer) { // not required
			return nil
		}

		if err := m.Producer.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("producer")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("producer")
			}
			return err
		}
	}

	return nil
}

func (m *InputOutputsIOArtifact) contextValidateValue(ctx context.Context, formats strfmt.Registry) error {

	if m.Value != nil {

		if swag.IsZero(m.Value) { // not required
			return nil
		}

		if err := m.Value.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("value")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("value")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InputOutputsIOArtifact) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InputOutputsIOArtifact) UnmarshalBinary(b []byte) error {
	var res InputOutputsIOArtifact
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
