// Code generated by go-swagger; DO NOT EDIT.

package run_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PipelineTaskDetailStatusMetadata Custom status metadata, this can be used to provide
// additional status info for a given task during runtime
//
// swagger:model PipelineTaskDetailStatusMetadata
type PipelineTaskDetailStatusMetadata struct {

	// custom properties
	CustomProperties map[string]interface{} `json:"custom_properties,omitempty"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this pipeline task detail status metadata
func (m *PipelineTaskDetailStatusMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pipeline task detail status metadata based on context it is used
func (m *PipelineTaskDetailStatusMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PipelineTaskDetailStatusMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PipelineTaskDetailStatusMetadata) UnmarshalBinary(b []byte) error {
	var res PipelineTaskDetailStatusMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
