// Code generated by go-swagger; DO NOT EDIT.

package run_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PipelineTaskDetailTaskPod pipeline task detail task pod
//
// swagger:model PipelineTaskDetailTaskPod
type PipelineTaskDetailTaskPod struct {

	// name
	Name string `json:"name,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// uid
	UID string `json:"uid,omitempty"`
}

// Validate validates this pipeline task detail task pod
func (m *PipelineTaskDetailTaskPod) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pipeline task detail task pod based on context it is used
func (m *PipelineTaskDetailTaskPod) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PipelineTaskDetailTaskPod) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PipelineTaskDetailTaskPod) UnmarshalBinary(b []byte) error {
	var res PipelineTaskDetailTaskPod
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
