// Code generated by go-swagger; DO NOT EDIT.

package artifact_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubeflow/pipelines/backend/api/v2beta1/go_http_client/artifact_model"
)

// GetMetricReader is a Reader for the GetMetric structure.
type GetMetricReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMetricReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMetricOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetMetricDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetMetricOK creates a GetMetricOK with default headers values
func NewGetMetricOK() *GetMetricOK {
	return &GetMetricOK{}
}

/*
GetMetricOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetMetricOK struct {
	Payload *artifact_model.V2beta1Artifact
}

// IsSuccess returns true when this get metric o k response has a 2xx status code
func (o *GetMetricOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get metric o k response has a 3xx status code
func (o *GetMetricOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get metric o k response has a 4xx status code
func (o *GetMetricOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get metric o k response has a 5xx status code
func (o *GetMetricOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get metric o k response a status code equal to that given
func (o *GetMetricOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get metric o k response
func (o *GetMetricOK) Code() int {
	return 200
}

func (o *GetMetricOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /apis/v2beta1/metrics/{artifact_id}][%d] getMetricOK %s", 200, payload)
}

func (o *GetMetricOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /apis/v2beta1/metrics/{artifact_id}][%d] getMetricOK %s", 200, payload)
}

func (o *GetMetricOK) GetPayload() *artifact_model.V2beta1Artifact {
	return o.Payload
}

func (o *GetMetricOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(artifact_model.V2beta1Artifact)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMetricDefault creates a GetMetricDefault with default headers values
func NewGetMetricDefault(code int) *GetMetricDefault {
	return &GetMetricDefault{
		_statusCode: code,
	}
}

/*
GetMetricDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetMetricDefault struct {
	_statusCode int

	Payload *artifact_model.GooglerpcStatus
}

// IsSuccess returns true when this get metric default response has a 2xx status code
func (o *GetMetricDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get metric default response has a 3xx status code
func (o *GetMetricDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get metric default response has a 4xx status code
func (o *GetMetricDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get metric default response has a 5xx status code
func (o *GetMetricDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get metric default response a status code equal to that given
func (o *GetMetricDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get metric default response
func (o *GetMetricDefault) Code() int {
	return o._statusCode
}

func (o *GetMetricDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /apis/v2beta1/metrics/{artifact_id}][%d] get_metric default %s", o._statusCode, payload)
}

func (o *GetMetricDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /apis/v2beta1/metrics/{artifact_id}][%d] get_metric default %s", o._statusCode, payload)
}

func (o *GetMetricDefault) GetPayload() *artifact_model.GooglerpcStatus {
	return o.Payload
}

func (o *GetMetricDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(artifact_model.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
