// Code generated by go-swagger; DO NOT EDIT.

package artifact_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kubeflow/pipelines/backend/api/v2beta1/go_http_client/artifact_model"
)

// NewLogMetricParams creates a new LogMetricParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLogMetricParams() *LogMetricParams {
	return &LogMetricParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLogMetricParamsWithTimeout creates a new LogMetricParams object
// with the ability to set a timeout on a request.
func NewLogMetricParamsWithTimeout(timeout time.Duration) *LogMetricParams {
	return &LogMetricParams{
		timeout: timeout,
	}
}

// NewLogMetricParamsWithContext creates a new LogMetricParams object
// with the ability to set a context for a request.
func NewLogMetricParamsWithContext(ctx context.Context) *LogMetricParams {
	return &LogMetricParams{
		Context: ctx,
	}
}

// NewLogMetricParamsWithHTTPClient creates a new LogMetricParams object
// with the ability to set a custom HTTPClient for a request.
func NewLogMetricParamsWithHTTPClient(client *http.Client) *LogMetricParams {
	return &LogMetricParams{
		HTTPClient: client,
	}
}

/*
LogMetricParams contains all the parameters to send to the API endpoint

	for the log metric operation.

	Typically these are written to a http.Request.
*/
type LogMetricParams struct {

	// Body.
	Body *artifact_model.V2beta1CreateArtifactRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the log metric params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LogMetricParams) WithDefaults() *LogMetricParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the log metric params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LogMetricParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the log metric params
func (o *LogMetricParams) WithTimeout(timeout time.Duration) *LogMetricParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the log metric params
func (o *LogMetricParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the log metric params
func (o *LogMetricParams) WithContext(ctx context.Context) *LogMetricParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the log metric params
func (o *LogMetricParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the log metric params
func (o *LogMetricParams) WithHTTPClient(client *http.Client) *LogMetricParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the log metric params
func (o *LogMetricParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the log metric params
func (o *LogMetricParams) WithBody(body *artifact_model.V2beta1CreateArtifactRequest) *LogMetricParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the log metric params
func (o *LogMetricParams) SetBody(body *artifact_model.V2beta1CreateArtifactRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *LogMetricParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
