// Code generated by go-swagger; DO NOT EDIT.

package artifact_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubeflow/pipelines/backend/api/v2beta1/go_http_client/artifact_model"
)

// LogMetricReader is a Reader for the LogMetric structure.
type LogMetricReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LogMetricReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLogMetricOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewLogMetricDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewLogMetricOK creates a LogMetricOK with default headers values
func NewLogMetricOK() *LogMetricOK {
	return &LogMetricOK{}
}

/*
LogMetricOK describes a response with status code 200, with default header values.

A successful response.
*/
type LogMetricOK struct {
	Payload *artifact_model.V2beta1Artifact
}

// IsSuccess returns true when this log metric o k response has a 2xx status code
func (o *LogMetricOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this log metric o k response has a 3xx status code
func (o *LogMetricOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this log metric o k response has a 4xx status code
func (o *LogMetricOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this log metric o k response has a 5xx status code
func (o *LogMetricOK) IsServerError() bool {
	return false
}

// IsCode returns true when this log metric o k response a status code equal to that given
func (o *LogMetricOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the log metric o k response
func (o *LogMetricOK) Code() int {
	return 200
}

func (o *LogMetricOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /apis/v2beta1/metrics][%d] logMetricOK %s", 200, payload)
}

func (o *LogMetricOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /apis/v2beta1/metrics][%d] logMetricOK %s", 200, payload)
}

func (o *LogMetricOK) GetPayload() *artifact_model.V2beta1Artifact {
	return o.Payload
}

func (o *LogMetricOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(artifact_model.V2beta1Artifact)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLogMetricDefault creates a LogMetricDefault with default headers values
func NewLogMetricDefault(code int) *LogMetricDefault {
	return &LogMetricDefault{
		_statusCode: code,
	}
}

/*
LogMetricDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type LogMetricDefault struct {
	_statusCode int

	Payload *artifact_model.GooglerpcStatus
}

// IsSuccess returns true when this log metric default response has a 2xx status code
func (o *LogMetricDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this log metric default response has a 3xx status code
func (o *LogMetricDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this log metric default response has a 4xx status code
func (o *LogMetricDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this log metric default response has a 5xx status code
func (o *LogMetricDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this log metric default response a status code equal to that given
func (o *LogMetricDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the log metric default response
func (o *LogMetricDefault) Code() int {
	return o._statusCode
}

func (o *LogMetricDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /apis/v2beta1/metrics][%d] log_metric default %s", o._statusCode, payload)
}

func (o *LogMetricDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /apis/v2beta1/metrics][%d] log_metric default %s", o._statusCode, payload)
}

func (o *LogMetricDefault) GetPayload() *artifact_model.GooglerpcStatus {
	return o.Payload
}

func (o *LogMetricDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(artifact_model.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
